### ISSUE TITLE
Is it a bug in RRCNN

### ISSUE THREAD

**Issue by qinhui99** [LeeJunHyun/Image_Segmentation#1]
I check this function and see the x has been changed by x = self.Conv_1x1(x).  So "return x+x1" maybe a bug.  
def forward(self,x):
        x = self.Conv_1x1(x)
        x1 = self.RCNN(x)
        return x+x1

**Comment by LeeJunHyun** [comment]
Dear @qinhui99 , I apologize for late response.

**Comment by LeeJunHyun** [comment]
If you have no further questions, I will close the issue. I hope my answer was helpful.
