### ISSUE TITLE
size problem

### ISSUE THREAD

**Issue by Nastu-Ho** [LeeJunHyun/Image_Segmentation#13]
Does this model have a requirement for image size?I have uesd 2 medical dataset in this model,but the results are strange.
这个模型对输入图片大小有要求吗？并且我的dataset是单通道图片，我把输入图片调整为三通道，但结果出来异常，有些指标很低

**Comment by LeeJunHyun** [comment]
Hi @Nastu-Ho , 

This code is implemented for ISIC images.
If you have different size of dataset, plz check the `data_loader.py`.
There are some codes for cropping and to resizing images, I think this part affect your results.

Thank you :)

**Comment by LeeJunHyun** [comment]
If you don't have further issues, I will close the issue. I hope my answer was helpful :)
