### ISSUE TITLE
predict image

### ISSUE THREAD

**Issue by vcvishal** [LeeJunHyun/Image_Segmentation#15]
how to get predicted segmented image from test data

**Comment by LeeJunHyun** [comment]
Hi, @vcvishal . 
There are code to obtain result images for validation data.
You can modify this for test data.

https://github.com/LeeJunHyun/Image_Segmentation/blob/master/solver.py#L231

**Comment by vcvishal** [comment]
thank you

**Comment by LeeJunHyun** [comment]
If you don't have further issues, I will close the issue. I hope my answer was helpful :)

**Comment by davidhuangal** [comment]
I modified the code found at https://github.com/LeeJunHyun/Image_Segmentation/blob/master/solver.py#L231
However, this only predicts one image per epoch. Is there a way to use a trained model to predict several images?

**Comment by mjiangtao** [comment]
> 每个纪元一个图像。有没有办法使用经过训练的模型来预测多个图像？

Do you solve the problem? Can you help me? Thank you.
