### ISSUE TITLE
batch_size about R2AttU_Net?

### ISSUE THREAD

**Issue by zhaoxuyan** [LeeJunHyun/Image_Segmentation#18]
I am using 1080ti
I set batch_size = 2 of R2AttU_Net, it return
`cuda runtime error (2) : out of memory`
Can I set batch_size > 1 when i training R2AttU_Net?

**Comment by LeeJunHyun** [comment]
Hi, @zhaoxuyan .
I think you should resize your input data, and fix `data_loader.py` code for pre-processing.
(ex. zero padding for different size of images.)
