### ISSUE TITLE
Order of the files

### ISSUE THREAD

**Issue by efc07** [LeeJunHyun/Image_Segmentation#20]
hi, What is the order of files that we need to run?

**Comment by LeeJunHyun** [comment]
Hi, @efc07 . 
I'm sorry but can you tell me what is exactly meaning of `order`?
just input output order?

**Comment by efc07** [comment]
I mean there are some python files.What should their working order?
Which one I should run firstly?

leejunhyun <notifications@github.com>, 19 Nis 2019 Cum, 10:48 tarihinde
şunu yazdı:

**Comment by LeeJunHyun** [comment]
If you already have prepared dataset, then just run `python main.py`.
else, run `python dataset.py` and then, `python main.py`.

**Comment by LeeJunHyun** [comment]
If you don't have further issues, I will close the issue. I hope my answer was helpful :)
