### ISSUE TITLE
Attention-Unet : IndexError: tuple index out of range

### ISSUE THREAD

**Issue by bigmb** [LeeJunHyun/Image_Segmentation#21]
Hey Lee, 
So I am wanted to implement Attention Unet. But there is some issue coming up while using it.
I am using my own dataset and also doing a lot of preprocessing with data.
When I am using your model I get this error.

![error](https://user-images.githubusercontent.com/14040051/57135433-bb15fa80-6dec-11e9-8e94-bdd0e0121473.png)

Any idea about it?
Its for medical binary segmentation

**Comment by LeeJunHyun** [comment]
Hi, @bigmb .
Can you try `torch.summary.summary(model_test1, input_size=(3,256,256))`?

**Comment by bigmb** [comment]
Hello,
Tried both.
So for the input size = 3,256,256
Got the same erorr.

Second gives an error as it expects 3 channel as the first input.

**Comment by LeeJunHyun** [comment]
Can you try this with ISIC data?

It seems that I need to check the mid status of `x` ~ `x4`

**Comment by bigmb** [comment]
Hey,
So I am not passing any images.
This just create a random variable of size (3,128,128).
It should just make a summary of the model. 
But still let me check with that dataset

**Comment by LeeJunHyun** [comment]
Yes, I also know that library, torchsummary.

I can't notice why it is not working for test Tensor. 

plz check the inference with real data.

**Comment by bigmb** [comment]
So I Checked with my own MRI data, Still the same issue.
I will try ISIC dataset in the weekend and let you know.

**Comment by bigmb** [comment]
I checked, so the issue is with torchsummary only , works after updating to pytorch 1.1.0.
Program runs when I run your original model too. 
So Closing the issue. It's related to TorchSummary , so don't run it.
