### ISSUE TITLE
Regarding dataset

### ISSUE THREAD

**Issue by kritipoddar123** [LeeJunHyun/Image_Segmentation#22]
How do I prepare my dataset ?

**Comment by LeeJunHyun** [comment]
Hi, @kritipoddar123 .

If you give me more specific issue, than I can help you.

**Comment by yejg2017** [comment]
Could you share me the trained model file?Thanks!

**Comment by LeeJunHyun** [comment]
Hi, @yejg2017 
Unfortunately, I don't have the trained model anymore.
Sorry.

**Comment by LeeJunHyun** [comment]
If you don't have further issues, I will close the issue.
