### ISSUE TITLE
some data info

### ISSUE THREAD

**Issue by DecentMakeover** [LeeJunHyun/Image_Segmentation#23]
Hi 
Thanks for sharing your work

I have a dataset which looks likes this, image of shape (26, 64,64,64),where in the image the 0th channel is the image and the and the 24 channels are labels, where each channel is a different label.

can i use my data to train this network ?
Let me know if you need more info
Thanks in advance

**Comment by LeeJunHyun** [comment]
Hi, @DecentMakeover .
Thank you for your interest about my code.

Sorry but I couldn't understand your data.
Is your data have shape  (26,64,64,64) ?
Could you please explain about each channel?

**Comment by DecentMakeover** [comment]
Nope the data is in patches (128, 128,128 ) , and simliar labels, labels have pixel values ranging from 0-25
The patches are numpy files.
What do you think?

**Comment by LeeJunHyun** [comment]
Okay, then what kind of problem you have?
transforming patches to Tensor? or obtaining proper output?
