### ISSUE TITLE
The result is not good in ISIC 2018

### ISSUE THREAD

**Issue by FENGShuanglang** [LeeJunHyun/Image_Segmentation#24]
Jaccard and  F1 only 0.5-0.7,are you sure? On the official competition website, the result common is 0.80+ in term of jaccard. In addition, the result of Unet in my experiment is 0.78+ in term of jaccard, Yes! ISIC 2018.  2594 images.I resize it to 256*192

**Comment by zz10001** [comment]
can you show how to train it?i just download the task one like this 
![image](https://user-images.githubusercontent.com/39954774/59261161-890b7a00-8c6f-11e9-95b1-9bb637722020.png)
what is the train/valid/test  train_GT/valid_GT/test_GT in dataset.py.
thx

**Comment by FENGShuanglang** [comment]
No,you can download this https://challenge.kitware.com/#phase/5abcb19a56357d0139260e53

**Comment by zz10001** [comment]
i downlaod from the link but when i extract，it only the some with what i show.and can you share you path in dataset.py like this.should i change something 
![image](https://user-images.githubusercontent.com/39954774/59268105-97ad5d80-8c7e-11e9-827a-053e5940a2e4.png)

**Comment by zz10001** [comment]
> No,you can download this https://challenge.kitware.com/#phase/5abcb19a56357d0139260e53

i can't find valid ground truth and test ground truth,when i run it .it occurs
![image](https://user-images.githubusercontent.com/39954774/59273836-af3f1300-8c8b-11e9-9b6e-856fb2b5f307.png)

**Comment by FENGShuanglang** [comment]
I download  and pre-process it in myself code

**Comment by LeeJunHyun** [comment]
Hi @FENGShuanglang .
The score can be differ according to train strategy such as optimizer, initialization, and early stopping.

**Comment by LeeJunHyun** [comment]
If you don't have further issues, I will close the issue. I hope my answer was helpful :)
