### ISSUE TITLE
some detail in  network

### ISSUE THREAD

**Issue by wydhenjoy** [LeeJunHyun/Image_Segmentation#28]
how can i see the result about the segmentation through the photos

**Comment by LeeJunHyun** [comment]
Hi, @wydhenjoy .
you can refer [solver.py#L232](https://github.com/LeeJunHyun/Image_Segmentation/blob/master/solver.py#L232).

**Comment by LeeJunHyun** [comment]
If you don't have any further issue, I will close this issue.
I hope that my comment was helpful :)
