### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 512, 512, 3] to have 3 channels, but got 512 channels instead

### ISSUE THREAD

**Issue by BillGreenHand** [LeeJunHyun/Image_Segmentation#29]
thanks for your share,i am trying to use your program to run my dataset,the train picture's size is 512,512,its channel is 3,but when i run this program ,it  appear this error, i don't know how to solve it,you know?thanks!
RuntimeError: Given groups=1, weight of size 64 3 3 3, expected input[1, 512, 512, 3] to have 3 channels, but got 512 channels instead

**Comment by LeeJunHyun** [comment]
Hi, @BillGreenHand .
I think you should transpose your dataset to have [3,512,512].
Could you please try this?

**Comment by BillGreenHand** [comment]
Thanks a lot, I have solved this problem.

**Comment by LeeJunHyun** [comment]
Good for you!
If you have further issue, then pleas let me know.
I'm gonna close this issue.
Thank you for your interest about my repo :)
