### ISSUE TITLE
about label issue

### ISSUE THREAD

**Issue by kangyang94** [LeeJunHyun/Image_Segmentation#3]
I change the background to 0 and others to 1 in my labels.But when I save the GT that is loaded from dataloader as a image, I get a image full of 0. Do you know why it happened?

**Comment by kangyang94** [comment]
And the code may not have a test function?

**Comment by LeeJunHyun** [comment]
can you try GT_np = GT.cpu().data.numpy()** *255 ** or GT_np = GT.cpu().numpy()** *255 **??

**Comment by LeeJunHyun** [comment]
If you have no further questions, I will close the issue. I hope my answer was helpful.

**Comment by kangyang94** [comment]
@LeeJunHyun Thank you very much.It works.
