### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by loaysh2010** [LeeJunHyun/Image_Segmentation#30]
Dear @LeeJunHyun ,
Thank you very much for your time and your help.
I want to ask you about the results image. Firstly my dataset used in model look like
![TCGA-18-5592-01Z-00-DX1-exp 0](https://user-images.githubusercontent.com/24863268/60046870-ab1de700-96c8-11e9-87a7-6e77f43373b5.png) --- ![TCGA-18-5592-01Z-00-DX1-exp 0](https://user-images.githubusercontent.com/24863268/60046882-b4a74f00-96c8-11e9-80e5-a00884675cab.png) for input and GT respectivly.
the getting result look like
![U_Net_valid_1_GT](https://user-images.githubusercontent.com/24863268/60046971-e5878400-96c8-11e9-8b8a-5a3c2eb17c3c.png) Named : U_Net_valid_1_GT
![U_Net_valid_1_image](https://user-images.githubusercontent.com/24863268/60046973-e6201a80-96c8-11e9-8c2d-6b432ddaf24b.png) Named : U_Net_valid_1_image
![U_Net_valid_1_SR](https://user-images.githubusercontent.com/24863268/60046974-e6201a80-96c8-11e9-9559-78ceb7b4e034.png) Named : U_Net_valid_1_SR
Can you please explain what's this images refer to ?!!!,, Where is the resulted segmented image?

**Comment by LeeJunHyun** [comment]
Dear @loaysh2010 ,
Thank you for your interest about my repo.
`U_Net_valid_1_GT` also seems like grayscale.
Is this right?

**Comment by loaysh2010** [comment]
Dear @LeeJunHyun 
Thank you for your quick response and concern.
Here is my Dataset samples for train and validation and test (input image and GT image ) respectively.
![TCGA-18-5592-01Z-00-DX1-exp 0](https://user-images.githubusercontent.com/24863268/60125221-a53d0a00-978b-11e9-80b2-cfdf5745c8b6.png) ==== ![TCGA-18-5592-01Z-00-DX1-exp 0](https://user-images.githubusercontent.com/24863268/60125224-a837fa80-978b-11e9-96ab-616fb89aa908.png)
![TCGA-18-5592-01Z-00-DX1-exp 16](https://user-images.githubusercontent.com/24863268/60125255-b5ed8000-978b-11e9-9ef7-b1b8b3b2a4b1.png) ==== ![TCGA-18-5592-01Z-00-DX1-exp 16](https://user-images.githubusercontent.com/24863268/60125258-b9810700-978b-11e9-8ba1-7fb7a723ca1b.png)
![TCGA-18-5592-01Z-00-DX1-exp 28](https://user-images.githubusercontent.com/24863268/60125279-c271d880-978b-11e9-8d27-31fa706fa592.png) ====
![TCGA-18-5592-01Z-00-DX1-exp 28](https://user-images.githubusercontent.com/24863268/60125296-c867b980-978b-11e9-8ada-3579092ab05b.png)

In the results, except the input image and that patch size is 5 all output is ambiguous for me. I think there is something in the code I have to adapt.
all my images (both input and GT) are [1,3,256,256]. What do you think I did wrong?

**Comment by loaysh2010** [comment]
@LeeJunHyun 
I solved the problem here. There is an error in the GT path given to the model. after correcting GT path the model gave excellent results. Thank you for your time and you can close the issue
