### ISSUE TITLE
Execution files order

### ISSUE THREAD

**Issue by AmericaBG** [LeeJunHyun/Image_Segmentation#32]
Hi!
First of all thank you very much for sharing your code!
I'd like to try it but I'm a little confused with the order in which I have to run the different files.

Could you help me?

Thank you very much!

**Comment by LeeJunHyun** [comment]
Hi, @SouthAmericaB .
Thank you for your interest about my code.
If you already have your own data split, then just run `main.py`.
Else, run `dataset.py` to split your dataset.
