### ISSUE TITLE
input size

### ISSUE THREAD

**Issue by ykeivn** [LeeJunHyun/Image_Segmentation#33]
Thanks for you sharing. 
I want to know shouldn't the input of the image be of any size?And I modified the file of data_loader,but I got this error:
d4 = torch.cat((x3,d4),dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 24 and 25 in dimension 2 at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorMath.cu:71
Please help me.

**Comment by Abe404** [comment]
I had a similar problem and was able to fix it by changing my image patch size from 572x572 to 576x576

**Comment by LeeJunHyun** [comment]
Hi, all.
At first, I am sorry to make you confused.
Could you please try batch size 1 ?

**Comment by davidhuangal** [comment]
@ykeivn Did you find a fix to this?
