### ISSUE TITLE
Problems about JS=1 & DC>1

### ISSUE THREAD

**Issue by Yiyiyimu** [LeeJunHyun/Image_Segmentation#41]
First of all, thank you for your code where I do learned a lot from. I work on a dataset looks like isic2018 where only got one category and around 900 images for training.

But I occur to a problem that when training, JS would keep equal to 1 and DC would even keeps greater than 1. I can't find reason since normalization in data_loader has already make sure DC could not larger than 1. Do you have any ideas?

I noticed things would happens when I use R2Unet and when SR output is totally black(nothing is divided out), maybe that would be helpful to find out where got something wrong.

Another problem is it seems the model cannot learn things during epoches processing, the best model would come out in first 5 epoches when training for like 200 epoches. Is that because model would get better result on small set and when it generalized to more images the score would drop? 
By the way, implementing only U-net would not get DC>1 and get some result.

Thank you in advance for your help~

-----------------------------------
Edit:
Just found out JS would also stuck on 1.0 and DC greater than 1 when training Attention U-net but this time it get some result. So it maybe just JS and DC calculation problem
No way this time same situation happens to U-net and I changed nothing...

**Comment by Yiyiyimu** [comment]
The original image looks like this
![C3-1_C001S0001_1](https://user-images.githubusercontent.com/34589752/64490290-0d30c600-d28e-11e9-981c-3dc90b3852a9.jpg)
and the output of image processed and normalized looks like this(save out at validation step)
![R2U_Net_valid_1_image](https://user-images.githubusercontent.com/34589752/64490311-36515680-d28e-11e9-92d3-2e1178899c19.png)
So it seems not being normalized right? Cause you can find white and black on the same image so they are still range from 0 to 255. It seems weird to me

**Comment by Yiyiyimu** [comment]
DC and JS give possible values when I change evaluation function to  (eg. DC)
```
def get_DC(SR,GT,threshold=0.5):
    # DC : Dice Coefficient
    SR = (SR > threshold).view(-1)
    GT = (GT == torch.max(GT)).view(-1)

    Inter = (SR*GT).sum()
    DC = float(2*Inter)/(float(SR.sum()+GT.sum()) + 1e-6)

    return DC
```

So basicly just change torch.max() to original array max, maybe there is something wrong here?

**Comment by Yiyiyimu** [comment]
Seems the problem is solved, so I'd close this issue. Again, thank you for your contribution!

**Comment by CN-zdy** [comment]
Hi, @Yiyiyimu 
How was the problem solved?
Could you help me?
Thank you very much!

**Comment by CN-zdy** [comment]
@Yiyiyimu 
Could you help me?
In my test, SE & SP  would  keeps greater than 1.
Can you give me some advice?
