### ISSUE TITLE
evalution problem

### ISSUE THREAD

**Issue by CN-zdy** [LeeJunHyun/Image_Segmentation#42]
Hi, @LeeJunHyun ,
First of all thank you very much for sharing your code!

i try with my data, but evalution score become 0.
i don't konw how to  to solve this problem. Is there something wrong with my data?

Epoch [1/50], Loss: 21.7333, 
[Training] Acc: 0.9116, SE: 0.0035, SP: 0.9902, PC: 0.0123, F1: 0.0053, JS: 0.0029, DC: 0.0053
[Validation] Acc: 0.9193, SE: 0.0064, SP: 0.9651, PC: 0.0075, F1: 0.0062, JS: 0.0031, DC: 0.0062
Best U_Net model score : 0.0094
Epoch [2/50], Loss: 18.3222, 
[Training] Acc: 0.9222, SE: 0.0000, SP: 0.9978, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9511, SE: 0.0003, SP: 0.9993, PC: 0.0053, F1: 0.0005, JS: 0.0003, DC: 0.0005
Epoch [3/50], Loss: 17.2257, 
[Training] Acc: 0.9309, SE: 0.0000, SP: 0.9988, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9452, SE: 0.0000, SP: 0.9931, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [4/50], Loss: 16.3815, 
[Training] Acc: 0.9266, SE: 0.0000, SP: 0.9991, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9514, SE: 0.0000, SP: 0.9997, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [5/50], Loss: 15.9624, 
[Training] Acc: 0.9243, SE: 0.0000, SP: 0.9996, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [6/50], Loss: 14.9182, 
[Training] Acc: 0.9232, SE: 0.0000, SP: 0.9998, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9517, SE: 0.0000, SP: 0.9999, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [7/50], Loss: 14.1974, 
[Training] Acc: 0.9235, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [8/50], Loss: 13.5342, 
[Training] Acc: 0.9233, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [9/50], Loss: 12.9099, 
[Training] Acc: 0.9241, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [10/50], Loss: 12.3084, 
[Training] Acc: 0.9281, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9516, SE: 0.0000, SP: 0.9998, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [11/50], Loss: 11.7281, 
[Training] Acc: 0.9264, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9519, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [12/50], Loss: 11.1690, 
[Training] Acc: 0.9278, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [13/50], Loss: 10.6329, 
[Training] Acc: 0.9204, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9519, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [14/50], Loss: 10.1158, 
[Training] Acc: 0.9211, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [15/50], Loss: 9.6117, 
[Training] Acc: 0.9295, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [16/50], Loss: 9.1243, 
[Training] Acc: 0.9213, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [17/50], Loss: 8.6579, 
[Training] Acc: 0.9218, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [18/50], Loss: 8.2152, 
[Training] Acc: 0.9244, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [19/50], Loss: 7.7921, 
[Training] Acc: 0.9160, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [20/50], Loss: 7.3884, 
[Training] Acc: 0.9207, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [21/50], Loss: 7.0041, 
[Training] Acc: 0.9297, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.9519, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [22/50], Loss: 6.6437, 
[Training] Acc: 0.9232, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 0.00010942264264529794.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [23/50], Loss: 6.3045, 
[Training] Acc: 0.9282, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 0.00010551469112225158.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [24/50], Loss: 5.9960, 
[Training] Acc: 0.9249, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 0.00010160673959920523.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [25/50], Loss: 5.7120, 
[Training] Acc: 0.9274, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 9.769878807615888e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [26/50], Loss: 5.4525, 
[Training] Acc: 0.9254, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 9.379083655311253e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [27/50], Loss: 5.2159, 
[Training] Acc: 0.9208, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 8.988288503006618e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [28/50], Loss: 4.9962, 
[Training] Acc: 0.9220, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 8.597493350701983e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [29/50], Loss: 4.7708, 
[Training] Acc: 0.9227, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 8.206698198397348e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [30/50], Loss: 4.5739, 
[Training] Acc: 0.9244, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 7.815903046092712e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [31/50], Loss: 4.4050, 
[Training] Acc: 0.9203, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 7.425107893788077e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [32/50], Loss: 4.2477, 
[Training] Acc: 0.9261, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 7.034312741483442e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [33/50], Loss: 4.1065, 
[Training] Acc: 0.9239, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 6.643517589178807e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [34/50], Loss: 3.9750, 
[Training] Acc: 0.9262, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 6.252722436874172e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [35/50], Loss: 3.8508, 
[Training] Acc: 0.9244, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 5.861927284569537e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [36/50], Loss: 3.7409, 
[Training] Acc: 0.9259, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 5.4711321322649015e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [37/50], Loss: 3.6415, 
[Training] Acc: 0.9278, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 5.0803369799602664e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [38/50], Loss: 3.5523, 
[Training] Acc: 0.9285, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 4.689541827655631e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [39/50], Loss: 3.4731, 
[Training] Acc: 0.9208, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 4.298746675350996e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [40/50], Loss: 3.3990, 
[Training] Acc: 0.9242, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 3.907951523046361e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [41/50], Loss: 3.3331, 
[Training] Acc: 0.9274, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 3.517156370741726e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [42/50], Loss: 3.2744, 
[Training] Acc: 0.9280, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 3.1263612184370907e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [43/50], Loss: 3.2240, 
[Training] Acc: 0.9264, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 2.735566066132455e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [44/50], Loss: 3.1804, 
[Training] Acc: 0.9221, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 2.3447709138278197e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [45/50], Loss: 3.1397, 
[Training] Acc: 0.9278, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 1.9539757615231842e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [46/50], Loss: 3.1074, 
[Training] Acc: 0.9281, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 1.5631806092185487e-05.
[Validation] Acc: 0.9519, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [47/50], Loss: 3.0812, 
[Training] Acc: 0.9264, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 1.1723854569139132e-05.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [48/50], Loss: 3.0632, 
[Training] Acc: 0.9187, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 7.815903046092777e-06.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [49/50], Loss: 3.0484, 
[Training] Acc: 0.9197, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 3.907951523046423e-06.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [50/50], Loss: 3.0376, 
[Training] Acc: 0.9241, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Decay learning rate to lr: 6.776263578034403e-20.
[Validation] Acc: 0.9518, SE: 0.0000, SP: 1.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000

Process finished with exit code 0

Could you help me?

Thank you very much!

**Comment by Yiyiyimu** [comment]
You could try on ISIC dataset if you change the code somehow. I guess maybe somewhere of the format of your input dataset is wrong

**Comment by CN-zdy** [comment]
@Yiyiyimu @LeeJunHyun Thank you very much!
I try on ISIC2018, it's good!

**Comment by Sweetnehi** [comment]
Do you havae sove it?
