### ISSUE TITLE
I'm just beginning to learn. I have a problem that I can't solve. Can you help me

### ISSUE THREAD

**Issue by yzuzhangxr** [LeeJunHyun/Image_Segmentation#44]
![微信截图_20191104144120](https://user-images.githubusercontent.com/57342484/68103319-32018c80-ff11-11e9-8822-b0a2a6a8d888.png)

**Comment by Yanxingang** [comment]
This is loading the weight you have trained.

**Comment by Morton9** [comment]
If most of the evaluation functions are 0, it is recommended to modify the evaluation function.
