### ISSUE TITLE
how to solve ?

### ISSUE THREAD

**Issue by PanPan0210** [LeeJunHyun/Image_Segmentation#5]
my label is  background to 0 and others to 1 .but i donot know how to make it work, the code may not have a test function?

**Comment by LeeJunHyun** [comment]
which test function do you mean?

**Comment by LeeJunHyun** [comment]
And you can refer [this issue](https://github.com/LeeJunHyun/Image_Segmentation/issues/4)

**Comment by PanPan0210** [comment]
ok,i will see .
now i have another question 
`Traceback (most recent call last):
  File "/home/panpan/wenjian/master/main.py", line 101, in <module>
    main(config)
  File "/home/panpan/wenjian/master/main.py", line 56, in main
    solver = Solver(config, train_loader, valid_loader, test_loader)
  File "/home/panpan/wenjian/master/solver.py", line 50, in __init__
    self.device = torch.device('cuda'if torch.cuda.is_available() else 'cpu')
AttributeError: module 'torch' has no attribute 'device'`    i donot know how to solve it

**Comment by LeeJunHyun** [comment]
Check your pytorch version and refer [here](https://pytorch.org/docs/master/tensor_attributes.html#device-doc) :)

**Comment by PanPan0210** [comment]
It still won't work after reinstallation，

**Comment by LeeJunHyun** [comment]
If you don't have further questions, I will close the issue. I hope my answer was helpful.
