### ISSUE TITLE
JS=1 and DC>1 when using ISIC2018 data

### ISSUE THREAD

**Issue by yuheng222** [LeeJunHyun/Image_Segmentation#51]
Hi there,

I tried to train a model using the ISIC2018 data (2594 images with 70/10/20 split) but the JS score is always 1 and DC score is always >1.

![Screenshot from 2020-02-14 22-06-18](https://user-images.githubusercontent.com/19872550/74538043-46284180-4f76-11ea-8917-514eb74c80b8.png)

I suspect that it might be due to my version of torch (1.2.0), torchvision (0.4.0) and pillow (6.2.0). Previously I was using torch (1.3.1), torchvision (0.4.2) and pillow (6.2.1) and my other scores were all 0 except for accuracy.

May I know what version of torch, torchvision and pillow you were using for this project? Thanks!

**Comment by DeVriesMatt** [comment]
Any update on this? Getting similar results

**Comment by pangda72** [comment]
> Hi there,
> 
> I tried to train a model using the ISIC2018 data (2594 images with 70/10/20 split) but the JS score is always 1 and DC score is always >1.
> 
> ![Screenshot from 2020-02-14 22-06-18](https://user-images.githubusercontent.com/19872550/74538043-46284180-4f76-11ea-8917-514eb74c80b8.png)
> 
> I suspect that it might be due to my version of torch (1.2.0), torchvision (0.4.0) and pillow (6.2.0). Previously I was using torch (1.3.1), torchvision (0.4.2) and pillow (6.2.1) and my other scores were all 0 except for accuracy.
> 
> May I know what version of torch, torchvision and pillow you were using for this project? Thanks!
Hi,yuheng222
I got the same results too,I don't know how to solve it .Have you solved the problem yet?If it's settled, could you help me to solve it?thanks in advance.

**Comment by pangda72** [comment]
> Any update on this? Getting similar results

Hi,DeVriesMatt
Sorry to bother you.I got similar results.Have you solved the problem yet.If it's settled, could you help me to solve it?
thanks in advance.

**Comment by pangda72** [comment]
> Any update on this? Getting similar results

Hi,DeVriesMatt
Sorry to bother you.I got similar results.Have you solved the problem yet.If it's settled, could you help me to solve it?
thanks in advance.
