### ISSUE TITLE
SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000

### ISSUE THREAD

**Issue by gdut3118007086** [LeeJunHyun/Image_Segmentation#54]
[Training] Acc: 0.6241, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7816, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [42/250], Loss: 0.0649, 
[Training] Acc: 0.6238, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7816, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [43/250], Loss: 0.0613, 
[Training] Acc: 0.6243, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7814, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [44/250], Loss: 0.0590, 
[Training] Acc: 0.6240, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7815, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [45/250], Loss: 0.0560,
[Training] Acc: 0.6242, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7815, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [46/250], Loss: 0.0539,
[Training] Acc: 0.6240, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7815, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [47/250], Loss: 0.0517,
[Training] Acc: 0.6239, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
[Validation] Acc: 0.7816, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
Epoch [48/250], Loss: 0.0492,
[Training] Acc: 0.6242, SE: 0.0000, SP: 0.0000, PC: 0.0000, F1: 0.0000, JS: 0.0000, DC: 0.0000
PS C:\Users\Egp\Desktop\Image_Segmentation-master>

i train on my own data. i don'know why. can u help me ?

**Comment by gdut3118007086** [comment]
pytorch 1.1.0

**Comment by Qy19970630** [comment]
Did you solve the problem?

**Comment by P9J7** [comment]
I got the same problem，did you slove it?

**Comment by caixhstrive** [comment]
I got the same problem，did you slove it?

**Comment by aliwaqas333** [comment]
same.

**Comment by P9J7** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
