### ISSUE TITLE
No results after long training on window10

### ISSUE THREAD

**Issue by wjj001-dl** [LeeJunHyun/Image_Segmentation#56]
Hellow,i have run this program on window10,but there is no results after long training,could you help me,thanks.
![image](https://user-images.githubusercontent.com/54653253/80295931-ae32a980-87a9-11ea-9419-2302bec7f2ab.png)

**Comment by small-rocket** [comment]
I have the same problem on Mac.

**Comment by small-rocket** [comment]
You can reduce the number of picture in dataset to test the program. For example, you can just leave 10 pictures in every folder of dataset.

**Comment by wjj001-dl** [comment]
> You can reduce the number of picture in dataset to test the program. For example, you can just leave 10 pictures in every folder of dataset.

thank you very much
