### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by kangyang94** [LeeJunHyun/Image_Segmentation#6]
Hello, could you upload the  ISIC 2018 dataset? I downloaded from the web but always failed in about 50%.

**Comment by LeeJunHyun** [comment]
Dear @kangyang94 , I am sorry but I didn't have ISIC dataset anymore.....

**Comment by LeeJunHyun** [comment]
If you don't have further questions, I will close the issue. I hope my answer was helpful :)
