### ISSUE TITLE
question about mode:test

### ISSUE THREAD

**Issue by dearladyli** [LeeJunHyun/Image_Segmentation#60]
Thank you for sharing code!
I want to run "test" mode and I try to run "python main.py  --mode test", then I have a error:" AttributeError: 'Solver' object has no attribute 'test'"
I wonder how to run "test" mode, could you help me ?
Thank you very much!

**Comment by zhangtongzan** [comment]
I also encountered this problem, how to modify it

**Comment by chen-yuu** [comment]
Has this problem been solved?

**Comment by BruceHan98** [comment]
Cause there is no 'test()' function in 'solver.py'
