### ISSUE TITLE
you can change TP and FN like this. TP = ((SR==1).byte()+(GT==1).byte())==2 .FN = ((SR==0).byte()+(GT==1).byte())==2.

### ISSUE THREAD

**Issue by jiudawn** [LeeJunHyun/Image_Segmentation#63]
you can change TP and FN like this. TP = ((SR==1).byte()+(GT==1).byte())==2 .FN = ((SR==0).byte()+(GT==1).byte())==2.a1==

_Originally posted by @wellfrogliu in https://github.com/LeeJunHyun/Image_Segmentation/issues/58#issuecomment-664729127_

problem solved!

**Comment by jiudawn** [comment]
SP = float(torch.sum(TN))/(float(torch.sum(TN+FP)) + 1e-6)
should also change "torch.sum(TN+FP)" to torch.sum(TN) + torch.sum(FP)

**Comment by rgd66** [comment]
Hello！ I can't get the score of JS and DC, JS=0, DC=0. How to solve this problem?

**Comment by WAHSIM** [comment]
> Hello！ I can't get the score of JS and DC, JS=0, DC=0. How to solve this problem?

you can change it this way. Inter=torch.sum((SR.byte()+GT.byte())==2). the rest can be done in the same manner.

**Comment by lifuguan** [comment]
Thanks!
