### ISSUE TITLE
how to custom the dataset folder?

### ISSUE THREAD

**Issue by zhou-rui1** [LeeJunHyun/Image_Segmentation#67]
Hi, I always get naming error when loading my own dataset:
`FileNotFoundError: [Errno 2] No such file or directory: './dataset/train_GT./dataset/train/32.png'
`
My folder structure:
––dataset
——train
———0.jpg
———1.jpg
——train_GT
———0.png
———1.png
is there something wrong with the filename? and I  change GT_path as follows:
`	def __getitem__(self, index):
		
		image_path = self.image_paths[index]
		filename = image_path.split('_')[-1][:-len(".jpg")]
		GT_path = self.GT_paths + filename + '.png'`
Any help would be so grateful!

**Comment by 1724706180** [comment]
you can  change codes like this: image_path = self.image_paths[index]
		filename = image_path.split('/')[-1][:-len(".jpg")]
		GT_path = self.GT_paths  + filename + '.png'
