### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by mengluchu** [LeeJunHyun/Image_Segmentation#69]
I got "tuple index out of range" with the Attention Unet.

**Comment by comradeLi** [comment]
Delete "g="and "x=" works.
Example:
x4 = self.Att5(g=d5,x=x4)→x4 = self.Att5(d5, x4)

**Comment by gstaryu** [comment]
> 

You are right, but why?

**Comment by gstaryu** [comment]
> Delete "g="and "x=" works. Example: x4 = self.Att5(g=d5,x=x4)→x4 = self.Att5(d5, x4)

You are right, but why?
