### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by Jorisfournel** [LeeJunHyun/Image_Segmentation#7]
Hello,

First of all thank you for your contribution.
Could you please point us what is to be changed in your code in order
to apply those networks to a custom dataset?

Thanks!!
Joris

**Comment by LeeJunHyun** [comment]
Dear @Jorisfournel , I appreciate about your interest.

At [main.py#L93](https://github.com/LeeJunHyun/Image_Segmentation/blob/master/main.py#L93), you can change the path to your own dataset directory if your dataset already split train/valid/test.
In this case, you should save your ground truth data at `TRAIN_PATH_NAME + _GT/`,`VALID_PATH_NAME + _GT/`,`TEST_PATH_NAME + _GT/`

else,  you can change the path of [dataset.py#L99](https://github.com/LeeJunHyun/Image_Segmentation/blob/master/dataset.py#L99), if you have only the split image/groud truth. And  then run `dataset.py`.

or you can use argparser like 
`main.py --train_path='YOUR_TRAIN_IMG_PATH' --valid_path='YOUR_VALID_IMG_PATH' --test_path='YOUR_TEST_IMG_PATH'`

or

`dataset.py --origin_data_path='CUSTUM_IMAGE_PATH' --'origin_GT_path=CUSTUM_GROUND_TRUTH_PATH'`

If it not works, then plz leave more issues anytime :)

**Comment by LeeJunHyun** [comment]
If you don't have further questions, I will close the issue. I hope my answer was helpful :)

**Comment by loaysh2010** [comment]
Hello,
@LeeJunHyun 
I followed your instruction by changing the path to my data in dataset.py L99,100 .. but after running the code I got num of samples= 0 in all folders (train, valid, test)
