### ISSUE TITLE
JS=1,DS>1and loss>1000

### ISSUE THREAD

**Issue by kimjisoo12** [LeeJunHyun/Image_Segmentation#79]
Hello, SORRY to bother you, when I refocused m attention Unet on my custom dataset, I also encountered JS which was always 1 and DICE >1, I saw  previous comments, I changed Torch. Max to Max without any improvement, and my loss was always over 1000, what is the reason?

![223](https://user-images.githubusercontent.com/89247664/138193291-f70b102e-9e16-4494-bd42-576eafaacd11.png)

**Comment by Lloyd-Pottiger** [comment]
update the `evaluation.py` into the following version:
https://github.com/LeeJunHyun/Image_Segmentation/blob/35b98018bf7efcb733ec214200c0ebbdec797f28/evaluation.py
