### ISSUE TITLE
Information about custom dataset

### ISSUE THREAD

**Issue by HamzahNizami** [LeeJunHyun/Image_Segmentation#9]
Hi there I wanted to use your model to train my dataset and I was wondering what format I must label my dataset. 

Thanks in advance

**Comment by LeeJunHyun** [comment]
Hi @HamzahNizami , 
I used .png format which is provided by ISIC challenge, but you can use any kind of format supported by pytorch.

**Comment by LeeJunHyun** [comment]
If you don't have further issues, I will close the issue. I hope my answer was helpful :)
